name: Deploy to Shopify
on:
  workflow_call:
jobs:
  changes_check:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.changes.outputs.deploy }}
    steps:
      - uses: actions/checkout@v2
      - name: Check Files Changed
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            deploy:
              - './sections/**'
              - './assets/**'
              - './config/**'
              - './layout/**'
              - './locales/**'
              - './snippets/**'
              - './templates/**'
              - './package.json'
  deploy-to-production:
    if: github.ref == 'refs/heads/master' && needs.changes_check.outputs.deploy == 'true'
    needs: changes_check
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v1
      - name: Shopify
        uses: pgrimaud/action-shopify@master
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          THEME_PATH: ./
      - name: Notify Success to Slack
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "text": "Deployment to `Production` have been completed successfully :rocket: on `${{ github.repository }}` - https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify Failure to Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000",
                  "text": "Deployment to `Production` have been failed :cry: on `${{ github.repository }}` - https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
