name: Shopify Theme Check

on:
  workflow_call:

jobs:
  deploy_preview:
    environment:
      name: staging
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
        uses: actions/checkout@v3

      - name: Shopify Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: '.'
          token: ${{ github.token }}

      - name: 'Theme Deploy Preview'
        uses: wyugen/shopify-theme-action@v1
        with:
          SHOPIFY_STORE: ${{secrets.DP_SHOPIFY_STORE}}
          SHOPIFY_APP_PW: ${{secrets.DP_SHOPIFY_APP_PW}}
          SHOPIFY_API_KEY: ${{secrets.DP_SHOPIFY_API_KEY}}
          github-token: ${{secrets.GITHUB_TOKEN}}
