name: Shopify Theme Check

on:
  workflow_call:
  
jobs:
  shopify_check:    

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Shopify Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: '.'
          token: ${{ github.token }}
